server:
  port: 8012
  servlet:
    context-path: /
  tomcat:
    max-http-post-size: -1

# eureka server
eureka-defaultZone: http://192.170.1.205:8761/eureka

# spring boot admin
spring-boot-admin-url: http://192.170.1.205:7001

spring:

  # redis
  redis:
    host: 192.170.1.205
    port: 6379
    password:

logback:
  # 设置是否打印mybatis sql, 默认DEBUG，表示打印；设置为ERROR,则不打印
  sqlLevel: DEBUG
  # 设置root logger level, 默认ERROR，可设置为DEBUG, INFO, ERROR等
  rootLevel: INFO
  # 设置日志文件名称，默认server
  appName: server
  # 日志打印路径, 默认为当前路径下的logs目录
  logDir: logs

aliyun:
  accessKeyId: xxx
  accessSecret: xxx
  sms:
    openTemplate: "SMS_185841061"
    closeTemplate: "SMS_185811043"
    signName: "摩慧IT管家"
  call:
    template: "TTS_184820226"
    number: "02566040620"

email:
  hostServer: "smtp.qq.com"
  port: 465
  username: "liu951129@vip.qq.com"
  password: "tvuznqblpvaabihf"

# 微信接口
weChat:
  appId: xxx
  # 重置开发者密码后, 要重新配置此参数
  appSecret: xxx
